const Latin = {
  "Abies balsamea"         : "Balsam Fir",
  "Acer nigrum"            : "Black Maple",
  "Acer pensylvanicum"     : "Striped Maple",
  "Acer rubrum"            : "Red Maple ",
  "Acer saccharinum"       : "Silver Maple",
  "Acer saccharum"         : "Sugar Maple",
  "Acer spicatum"          : "Mountain Maple",
  "Acer x freemanii"       : "Swamp Maple",
  "Aesculus glabra"        : "Ohio Buckeye",
  "Aesculus octandra"      : "Yellow Buckeye",
  "Aesculus flava"         : "Yellow Buckeye",
  "Aesculus parviflora"    : "Bottlebrush Buckeye",
  "Aesculus pavia"         : "Red Buckeye",
  "Alnus rugosa"           : "Speckled Alder",
  "A. incana ssp. rugosa"  : "Speckled Alder",
  "Amelanchier laevis"     : "Smooth Serviceberry",
  "Asimina triloba"        : "Pawpaw",
  "Betula alleghaniensis"  : "Yellow Birch",
  "Betula lenta"           : "Cherry Birch",
  "Betula papyrifera"      : "Paper birch",
  "Betula pumila"          : "Dwarf Birch",
  "Carpinus caroliniana"   : "American hornbeam",
  "Carya cordiformis"      : "bitternut hickory",
  "Carya glabra"           : "Pignut Hickory",
  "Carya laciniosa"        : "Shellbark Hickory",
  "Carya ovalis"           : "Red Hickory",
  "Carya ovata"            : "shagbark hickory",
  "Carya tomentosa"        : "mockernut hickory",
  "Carya alba"             : "mockernut hickory",
  "Castanea dentata"       : "American Chestnut",
  "Celtis occidentalis"    : "hackberry",
  "Celtis tenuifolia"      : "dwarf hackberry",
  "Cercis canadensis"      : "redbud",
  "Cladrastis lutea"       : "yellowwood",
  "Cladrastis kentuckea"   : "yellowwood",
  "Cornus alternifolia"    : "alternate-leaf dogwood",
  "Cornus florida"         : "flowering dogwood",
  "Corylus cornuta"        : "Beaked Hazel",
  "Crataegus spp."         : "Hawthorn",
  "Fagus grandifolia"      : "American Beech",
  "Fraxinus americana"     : "White Ash",
  "Fraxinus nigra"         : "Black Ash",
  "Fraxinus pennsylvanica" : "Green Ash",
  "Fraxinus profunda"      : "Pumpkin Ash",
  "Fraxinus quadangulata"  : "Blue Ash",
  "Gleditsia triacanthos"  : "Honey Locust",
  "Gymnocladus dioicus"    : "Kentucky coffee tree",
  "Juglans cinerea"        : "Butternut",
  "Juglans nigra"          : "Black Walnut",
  "Juniperus virginiana"   : "Red Cedar",
  "Larix laricina"         : "Tamarack",
  "Liquidambar styraciflua": "sweetgum",
  "Liriodendron tulipifera": "tulip tree ",
  "Maclura pomifera"       : "Osage orange",
  "Magnolia acuminata"     : "Cucumber Tree",
  "Magnolia grandiflora"   : "southern magnolia",
  "Magnolia tripetala"     : "umbrella magnolia",
  "Malus coronaria"        : "Wild Crabapple",
  "Morus rubra"            : "Red Mulberry",
  "Nyssa sylvatica"        : "black gum ",
  "Ostrya virginiana"      : "Ironwood",
  "Picea glauca"           : "White Spruce",
  "Picea mariana"          : "Black Spruce",
  "Pinus banksiana"        : "Jack Pine",
  "Pinus strobus"          : "white pine ",
  "Platanus occidentalis"  : "American sycamore",
  "Populus balsamifera"    : "Balsam Poplar",
  "P. tacamahaca candicans": "Balsam Poplar",
  "Populus deltoides"      : "Eastern Cottonwood",
  "Populus grandidentata"  : "Largetooth Aspen",
  "Populus tremuloides"    : "Trembling Aspen",
  "Prunus americana"       : "American Plum",
  "Prunus nigra"           : "Canada plum",
  "Prunus pensylvanica"    : "Pin Cherry",
  "Prunus serotina"        : "black cherry",
  "Ptelea trifoliata"      : "hoptree",
  "Quercus alba"           : "White Oak",
  "Quercus bicolor"        : "Swamp White Oak",
  "Quercus ellipsoidalis"  : "Hill's Oak",
  "Quercus macrocarpa"     : "Bur Oak",
  "Quercus muehlenbergii"  : "Chinquapin Oak",
  "Quercus palustris"      : "Pin Oak",
  "Quercus prinoides"      : "Dwarf Chinkapin Oak",
  "Quercus rubra"          : "Red Oak",
  "Quercus shumardii"      : "Shumard Oak",
  "Quercus velutina"       : "Black Oak",
  "Salix amygdaloides"     : "Peachleaf Willow",
  "Salix petiolaris"       : "Slender Willow",
  "Sassafras albidum"      : "Sassafras",
  "Sorbus americana"       : "American Mountain-Ash",
  "Thuja occidentalis"     : "White Cedar",
  "Tilia americana"        : "Basswood",
  "Tsuga canadensis"       : "Hemlock",
  "Ulmus americana"        : "American or White Elm",
  "Ulmus rubra"            : "Slippery elm",
  "Ulmus thomasii"         : "Rock elm",
  "Zanthoxylum americanum" : "Prickly Ash"
}
export default Latin

