require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TreeSnap' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Fabric', '~> 1.7.7'
  pod 'Crashlytics', '~> 3.10.2'

  # Add new pods below this line
#  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
#  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
  
  
end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#      if target.name == 'react-native-google-maps'
#        target.build_configurations.each do |config|
#          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
#        end
#      end
#
#      # The following is needed to ensure the "archive" step works in XCode.
#      # It removes React & Yoga from the Pods project, as it is already included in the main project.
#      # Without this, you'd see errors when you archive like:
#      # "Multiple commands produce ... libReact.a"
#      # "Multiple commands produce ... libyoga.a"
#
#      targets_to_ignore = %w(React yoga)
#
#      if targets_to_ignore.include? target.name
#        target.remove_from_project
#      end
#
#    end
#end
